	export enum GamePhase {
	  MENU = 'MENU',
	  RECRUITING = 'RECRUITING',
	  PRESS_CONFERENCE = 'PRESS_CONFERENCE',
	  MATCH_PREP = 'MATCH_PREP',
	  MATCH = 'MATCH',
	  POST_MATCH = 'POST_MATCH'
	}
	
	export enum PlayerClass {
	  SNIPER = 'Sniper', // High scoring
	  ENFORCER = 'Enforcer', // High defense/hitting
	  PLAYMAKER = 'Playmaker', // High speed/assist
	  GOALIE = 'Goalie'
	}
	
	export interface GameStats {
	  swagger: number;
	  heat: number;
	  trust: number;
	  chemistry: number;
	}
	
	export interface Player {
	  id: string;
	  name: string;
	  nickname: string;
	  class: PlayerClass;
	  stats: {
	    speed: number;
	    shooting: number;
	    physicality: number;
	    chirp: number; // Morale damage
	  };
	  salary: number;
	  bio: string; // Generated by Gemini
	  energy: number;
	  gameStats: GameStats; // Added gameStats to Player interface
	}
	
	export interface Team {
	  name: string;
	  reputation: number;
	  budget: number;
	  roster: Player[];
	  wins: number;
	  losses: number;
	}
	
	export interface ChatMessage {
	  sender: 'Commissioner' | 'User' | 'Reporter' | 'Recruit';
	  text: string;
	}
	
	export interface MatchState {
	  timeRemaining: number;
	  score: { us: number; them: number };
	  puckPosition: { x: number; y: number }; // 0-100 scale
	  events: string[];
	  inProgress: boolean;
	}
